### ISSUE TITLE
Enhancement idea: measure hopcount

### ISSUE THREAD

**Issue by electroniceel** [benjojo/sping#20]
When measuring and comparing latency I find it quite valuable to also measure the hopcount between hosts. This immediately shows routing changes and can help to categorize reasons for latency changes when comparing measurements over time.

To measure hop count to a remote target you could use traceroute, but this will send much more packets than actually required. It would be much more efficient if something on the remote end would just record the hop count / ttl values it received and makes them available somehow.

I think this is something that would fit into sping very well. Always having the hopcount available together with the latency in the same metrics will help interpreting the latency values and their changes.

What do you think about this?

**Comment by benjojo** [comment]
I'm not sure this makes sense anymore when accounting for a modern day network that uses such things as MPLS or other segment routing technologies. 

Since the Hop count in those setups are greatly hidden ( a current example is trace routes going over the GTT network go in on one hop and “pop out” the other side of the world, exposing a single hop to the user who is tracerouting).

Overall I actually don't think that a TTL value does give you that much operationally useful information anymore beyond whether it is extremely low or not ( say less than 10 ), it does also not help that fetching such data from a linux kernel is not easy, and likely requires super user or NET_ADMIN rights.
